### ISSUE TITLE
Warning when starting container

### ISSUE THREAD

**Issue by emilsoman** [heyman/docker-postgres-backup#1]
I am using the docker image hosted here: https://hub.docker.com/r/heyman/postgresql-backup/ . When the container starts, it logs the following warning:

```sh
tail: unrecognized file system type 0x794c7630 for '/backup.log'. please report this to bug-coreutils@gnu.org. reverting to polling
```

A quick google search led me to this -> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810669 . Looks like this was a bug which got fixed.

Does the base image need updating?

**Comment by heyman** [comment]
I haven't seen that error (I have the image running for a couple of projects). Does it create backups, and do you see any log output when running `docker logs ...`? If so, I would guess that you can ignore the warning. Don't know if upgrading the base image might fix it.

**Comment by heyman** [comment]
Closing this issue since the image no longer uses tail to read the script output.
