### ISSUE TITLE
Error on dump and slack  notify ¿?

### ISSUE THREAD

**Issue by aalemanq** [heyman/docker-postgres-backup#15]
Hello, in one of my backups, I have a python error and no slack notification about this, someone know what can be?

postgres12, with postgres-backup:12 image. Tested on another postgres12 without any problem

```
[2021-04-28 08:54:35]: Dumping database
Command execution failed. Output:
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/backup/backup.py", line 143, in <module>
    main()
  File "/backup/backup.py", line 104, in main
    take_backup()
  File "/backup/backup.py", line 72, in take_backup
    cmd("pg_dump -Fc > %s" % backup_file, env=env)
  File "/backup/backup.py", line 50, in cmd
    subprocess.check_output([command], shell=True, stderr=subprocess.STDOUT, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pg_dump -Fc > /data/backups/xxx_2021-04-28']' returned non-zero exit status -9
```

If I execute manually with: 
```
pg_dump -h postgresql -U xxx -d xxxx  -Fc > /data/backups/xxxx-2021-04-28
```

I have this error:
```
bash-5.1# pg_dump -h postgresql -U xxxx -d xxxx  -Fc > /data/backups/xxxx-2021-04-28
Password: 
Killed
bash-5.1# 
```

ENVS:
```
HOSTNAME=8e25b6bea6c9
WEBHOOK_METHOD=POST
AWS_DEFAULT_REGION=XXXXX
WEBHOOK=https://hooks.slack.com/services/TFLCLAFEC/XXXXXX
PWD=/
CRON_SCHEDULE=15 3 * * *
PG_SHA256=df7dd98d5ccaf1f693c7e1d0d084e9fed7017ee248bba5be0167c42ad2d70a09
BACKUP_DIR=/data/backups
DB_USER=XXXX
HOME=/root
LANG=en_US.utf8
AWS_SECRET_ACCESS_KEY=XXXXXXX
WEBHOOK_CURL_OPTS=-H 'Content-type: application/json'
PG_MAJOR=12
PG_VERSION=12.6
TERM=xterm
DB_HOST=postgresql
WEBHOOK_DATA={"text":":white_check_mark: Backup completed at %(date)s %(time)s\nDuration: %(duration)s seconds\nUpload: %(filename)s: %(size)s"}
SHLVL=1
AWS_ACCESS_KEY_ID=XXXXXX
DB_NAME=XXXXXX
PGDATA=/var/lib/postgresql/data
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DB_PASS=XXXXXXX
S3_PATH=s3://XXXX/XXXXX
_=/usr/bin/env
```

Logs on postgres:
```
xxxxx.1.bdisbuks9y0a@dev-worker04    | 2021-04-28 08:55:10.455 UTC [6980] LOG:  unexpected EOF on client connection with an open transaction
```

**Comment by heyman** [comment]
Since the exit code is `-9` I suspect this might be the doing of the [OOM killer](https://lwn.net/Articles/317814/). That means the machine is running out of memory, and therefore must kill one or more processes to free up RAM. 

I assume you use the `WEBHOOK` environment variable to integrate with Slack? The `WEBHOOK` URL is only called upon normal/successful termination of the backup processes. Therefore, the fact that you don't get any notification in Slack is to be expected. I'd recommend using the `WEBHOOK` environment variable with something like [Healthchecks](https://github.com/healthchecks/healthchecks) to get alerted when a periodic job fails to execute within a certain time frame.

**Comment by aalemanq** [comment]
Hello Heyman!!  yes, was this, ram on postgresql....now is fixed

I have to check this that you are saying about failure healths because for now I just now if is success

Regards!!!

**Comment by heyman** [comment]
Glad to hear I could help.

I can really recommend Healthchecks for getting alerts of failed periodic jobs. They have a hosted version on https://healthchecks.io which is free up to some limit. You want to get notified if a backup job fails, not when it succeeds :).
