### ISSUE TITLE
Enhancement request to support the --endpoint-url flag from the AWS CLI

### ISSUE THREAD

**Issue by idoob** [heyman/docker-postgres-backup#9]
Is adding support for the ```--endpoint-url``` flag (more info [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-options.html)) something that can be supported? Although this is usually automatically set, it would be useful to have the ability to also define it manually if needed. Additionally, it would enable the ability to use postgresql-backup with other S3-compatible services like minio. I can try to submit a pull request if this is something that would be considered.

**Comment by heyman** [comment]
That sounds like a good addition! A PR would be welcome!

**Comment by tkhduracell** [comment]
Here it is #11

**Comment by heyman** [comment]
Fixed by @tkhduracell in #11!
